### ISSUE TITLE
Your color palette

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [hnmr293/ComfyUI-nodes-hnmr#2]
You have very nice tuning of color palette on the example shots. Do you mind sharing it please? Thank you.
https://github.com/hnmr293/ComfyUI-nodes-hnmr/blob/main/examples/workflow_mbw.png

**Comment by hnmr293** [comment]
It is default colors of old version ComfyUI. Please contact the author of main repo.

**Comment by viktor-zhuromskyy** [comment]
Thanks
